# Generated by Django 4.1.7 on 2023-03-14 10:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='owner',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
