# Generated by Django 4.1.7 on 2023-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0002_alter_files_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fileMetadata',
        ),
        migrations.AddField(
            model_name='files',
            name='RAIDid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='RAIDtype',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='SID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='actualSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
