# Generated by Django 4.1.7 on 2023-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0003_delete_filemetadata_files_raidid_files_raidtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='RAIDid',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='RAIDtype',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
