# Generated by Django 4.1.7 on 2023-03-19 09:48

import CVSMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0004_alter_files_raidid_alter_files_raidtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to=CVSMS.models.file_path),
        ),
    ]
