# Generated by Django 4.1.7 on 2023-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0006_alter_files_raidid_alter_files_raidtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='RAIDtype',
            field=models.CharField(choices=[('N', 'NONE'), ('P', 'PARITY'), ('1', '1'), ('0', '0')], default='N', max_length=1, null=True),
        ),
    ]
