# Generated by Django 4.1.7 on 2023-03-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0008_alter_files_raidid_alter_files_raidtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='storageNodeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.IntegerField()),
                ('allocSize', models.IntegerField()),
                ('IP', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='storageNodeMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID', models.IntegerField()),
                ('fileName', models.CharField(max_length=100)),
                ('fileSize', models.IntegerField()),
                ('start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='storageNodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='heartBeat',
        ),
        migrations.DeleteModel(
            name='storageNode',
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
