# Generated by Django 4.1.7 on 2023-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0009_storagenodeinfo_storagenodemetadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='storageNodeMetadata',
        ),
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='storagenodestatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
