# Generated by Django 4.1.7 on 2023-03-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0014_storagenodeinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='SID',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
