# Generated by Django 4.1.1 on 2023-05-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0015_alter_files_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='fileName',
            new_name='fName',
        ),
    ]
