# Generated by Django 4.1.7 on 2023-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0015_alter_files_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='fileName',
        ),
        migrations.AddField(
            model_name='files',
            name='fName',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
