# Generated by Django 4.1.1 on 2023-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0016_rename_filename_files_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='isCached',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
