# Generated by Django 4.2.1 on 2023-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVSMS', '0017_files_iscached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
